name: Continuous Integration
on:
  push:
    branches-ignore:
      - 'release-please**'
  pull_request:
    branches-ignore:
      - 'release-please**'

jobs:
  code-quality:
    name: Run code quality checks on PHP 7.4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: msgpack, igbinary
      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist
      - name: Run code quality checks
        run: vendor/bin/grumphp run --testsuite=code_quality
  php-test:
    name: Run tests on ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    needs: code-quality
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: msgpack, igbinary
      - name: Remove GrumPHP
        run: composer remove --dev phpro/grumphp
      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist
      - name: Install WordPress
        run: .github/workflows/install-wp.sh
      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite unit
      - name: Run integration tests
        env:
          AWS_TEST_ACCESS_KEY_ID: ${{ secrets.AWS_TEST_ACCESS_KEY_ID }}
          AWS_TEST_SECRET_ACCESS_KEY: ${{ secrets.AWS_TEST_SECRET_ACCESS_KEY }}
        run: vendor/bin/phpunit --testsuite integration
